### ISSUE TITLE
Scheduled command runs at different times

### ISSUE THREAD

**Issue by nakami** [sopel-irc/sopel#1172] opened 2017-02-07 16:04 UTC
Running sopel on CentOS release 6.8, Python 3.4.3.

I have a module containing a command that is supposed to run at UTC 0:00 + 2 minutes offset.
However, it runs at unexpected times, after the first successful run.

this is the relevant code:
```python
from sopel import module
from datetime import datetime

offset_seconds     = 60*2 # 2min
seconds_a_day           = 86400
channels                = ["#mybotchannel"]

def get_time_utc():
	return datetime.utcnow()

def get_seconds_to_midnight():
    utcnow = get_time_utc()
    sec_passed = utcnow.hour * 3600
    sec_passed += utcnow.minute * 60
    sec_passed += utcnow.second
    return seconds_a_day - sec_passed

def msg_multi_chan(bot, channels, message):
    for channel in channels:
        bot.msg(channel, message)

new_time = get_seconds_to_midnight() + offset_seconds 

@module.interval(new_time)
def run_at_midnight_plus_offset(bot):
	# init
    msg_multi_chan(bot, channels, bold("[Triggered]") +" this should trigger 2min after midnight")
    new_time = get_seconds_to_midnight() + offset_seconds
    return

@module.commands('debug')
def debug(bot, trigger):
    bot.say("seconds to midnight plus offset: " + str(get_seconds_to_midnight() + offset_seconds))
    return
```

first time:
`00:02:01 bot: [Triggered] this should trigger 2min after midnight` :heavy_check_mark:
same day, later:
`23:54:49 bot: [Triggered] this should trigger 2min after midnight` :heavy_multiplication_x:
day after:
`23:43:39 bot: [Triggered] this should trigger 2min after midnight` :heavy_multiplication_x:
day after:
`23:40:28 bot: [Triggered] this should trigger 2min after midnight` :heavy_multiplication_x:
day after:
`23:33:16 bot: [Triggered] this should trigger 2min after midnight` :heavy_multiplication_x:

however, my debug command returns the expected seconds value.
what did i screw up? is this expected behaviour?

**Comment by nakami** [comment] 2017-02-07 16:34
i guess the parameter of 
```python 
@module.interval(new_time)
```
is just set once and therefore contains the initial amount of seconds for the next runs.
is there any way to resolve my issue?
the first idea i come up with is hardcoding the interval to be a day in seconds and then starting the bot at the exact time i want it to run the command each day... meh.

**Comment by firerogue** [comment] 2017-02-07 16:44
Sopel expects the number passed in @module.interval to be a constant, not a
variable. Because of this it only checks the value when registering your
function, not on every pass.
So yes. This is expected behaviour.

**Comment by nakami** [comment] 2017-02-07 16:53
ah, it's that simple. argh. thanks.

so, is there a proper way to schedule things?

**Comment by dgw** [comment] 2018-03-25 07:01
"Proper"? No. I'll close this, as the feature of scheduling callables for a specific time (instead of an interval) is covered by #1222.

**Closed by dgw** 2018-03-25 07:01 UTC
Labels: Question

**Comment by ronilaukkarinen** [comment] 2020-06-30 17:19
@nakami Can you share the working script? Trying to figure out on how to get the sopel bot say something after midnight, cannot find any working example...

**Comment by ronilaukkarinen** [comment] 2021-02-23 21:26
Any hint?

**Comment by dgw** [comment] 2021-02-23 21:50
@ronilaukkarinen Did you visit the linked issue? https://github.com/sopel-irc/sopel/issues/1222#issuecomment-535830451 shows some approaches to this.
