### ISSUE TITLE
Does not connect to channels with ## prefix.

### ISSUE THREAD

**Issue by mB-PiBox** [sopel-irc/sopel#1073] opened 2016-05-02 23:18 UTC
Any channels in the list with ## prefix for channel name.
ie: #freenode,#archlinux,##arkwiki,#mmopg
all channels are connected to except ##arkwiki.

**Comment by mossarelli** [comment] 2016-05-03 15:04
Could you copy the entry for channels from the default.cfg?
We run a bot that only connects to one channel with a double # and it works fine.
`channels = ##fringe`

**Comment by mB-PiBox** [comment] 2016-05-03 22:37
channels = #arkwiki,##ArkBot,#arksurvival

**Comment by mossarelli** [comment] 2016-05-08 19:06
Try putting the ##channel first, put spaces between the commas.

`channels = ##arkbot, #arksurvival, #arkwiki`

**Comment by maxpowa** [comment] 2016-05-24 05:29
I'm unable to reproduce this, Sopel 6.3.1. Tried with the `##` channel first, middle and end of the channel list and they all worked fine. There's many reasons why the server could be preventing you from joining, we'd need at least a fresh raw.log output from your bot to determine if the `JOIN` commands are being rejected by the server.

**Comment by maxpowa** [comment] 2016-10-01 00:07
No info provided so I'm closing.

**Closed by maxpowa** 2016-10-01 00:07 UTC
Labels: Needs Info
