### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Darksider3** [sopel-irc/sopel#1179] opened 2017-03-03 12:26 UTC
Hey guys,

it looks alot like the maintainers abandoned the project... do you got any infos here?

**Comment by dasu** [comment] 2017-03-06 22:15
I doubt, but if it is you can always fork and take over. :P
@maxpowa @embolalia any comments?

**Comment by Darksider3** [comment] 2017-03-07 07:24
Nope, just wanted to know. Following this since early 2016, and got some self written plugins :P

It where only a "huh? Nothing?" Reaction xD I don't want to migrate the (my) plugins. :smile:

**Comment by dgw** [comment] 2017-03-07 07:50
I hope we can look forward to at least another version or two. There are some annoying bugs/regressions from the last few versions that I don't know enough about to fix, but certainly affect operation in some situations.

**Comment by maxpowa** [comment] 2017-03-07 18:32
I haven't run Sopel in a couple months and have been relatively busy with work/personal life, so I haven't had time or motivation to contribute as in the past.

**Comment by antdude** [comment] 2017-03-17 19:32
Oh good. Rbot is like dead with almost a year of no updates. I noticed Sopel had no updates since November too. It's good that you guys are still alive. :)

**Comment by dgw** [comment] 2018-03-23 11:19
Closing this, as I've taken over the role of maintainer.

**Closed by dgw** 2018-03-23 11:19 UTC
