### ISSUE TITLE
require_privilege strange behavior

### ISSUE THREAD

**Issue by ThijsEigenwijs** [sopel-irc/sopel#1594] opened 2019-05-10 07:52 UTC
When i tried to figure out what accesslevel i had on the server it first didnt work
(code: https://github.com/ThijsEigenwijs/sopel_require_permission/blob/master/accesslevel_doesntwork)

When i changed the orders of the @require_permission so the lowest was the first one to be called it did work
(code: https://github.com/ThijsEigenwijs/sopel_require_permission/blob/master/accesslevel)

I don't know if this is intented, but i found it strange, so here is my issue

Thanks in advance!
Thijseigenwijs

**Comment by dgw** [comment] 2019-05-10 08:41
Either something else weird was going on, or I don't understand what the issue was. In a channel where I am `+qo`, with your `accesslevel_doesntwork` plugin:

```
<dgw>        .admin
<SopelTest>  dgw: Youre an admin
<dgw>        .owner
<SopelTest>  dgw: your my owner
<dgw>        .voice
<SopelTest>  dgw: You may speak
<dgw>        .halfop
<SopelTest>  dgw: You have the permission halfop
<dgw>        .op
<SopelTest>  dgw: You are an operator
```

What "didnt work" in this version of the plugin that made you sort the functions by privilege level?

I expected to see multiple `@require_privilege` decorators on a single function, honestly. The decorators on different functions _cannot_ affect each other, so the order in which the functions are declared simply _cannot_ matter, so far as I know.

_(Because it sounds like an impossible bug, I'll close the issue. Feel free to continue discussion, though—we can reopen if there really is a problem. :smile_cat:)_

**Closed by dgw** 2019-05-10 08:41 UTC

**Comment by ThijsEigenwijs** [comment] 2019-05-10 08:43
If you only have +o it does behave strange, otherwise it might be an server issue

**Comment by dgw** [comment] 2019-05-10 08:44
> If you only have +o it does behave strange

_How_? Please describe, or show logs of the issue. Without any information beyond "strange", there's no way to diagnose anything or determine if there really is a bug.

**Comment by ThijsEigenwijs** [comment] 2019-05-10 08:48
doesnt work file
<thijseigenwijs_> .op
<thijseigenwijs_> .admin
<StroopwafelV2> Your not an admin
<thijseigenwijs_> .halfop
<thijseigenwijs_> .voice

Working file
<thijseigenwijs_> .op
<StroopwafelV2> Your not an operator
<thijseigenwijs_> .halfop
<StroopwafelV2> Your not a halfop

This is the chatlog out of Hexchat

**Comment by dgw** [comment] 2019-05-10 09:07
Played around some more, all with [the "not working" file](https://raw.githubusercontent.com/ThijsEigenwijs/sopel_require_permission/cddd28e39dbf6e7eb11a5619d60ef1ff1ec43f0b/accesslevel_doesntwork); still can't reproduce.

Tried with no privileges:

```
<dgw>        .owner
<SopelTest>  Your not the owner
<dgw>        .admin
<SopelTest>  Your not an admin
<dgw>        .voice
<SopelTest>  You're not voiced!
<dgw>        .halfop
<SopelTest>  Your not a halfop
<dgw>        .op
<SopelTest>  Your not an operator
```

Then gave myself `+o` only:

```
<@dgw>       .op
<SopelTest>  dgw: You are an operator
<@dgw>       .voice
<SopelTest>  dgw: You may speak
<@dgw>       .halfop
<SopelTest>  dgw: You have the permission halfop
<@dgw>       .admin
<SopelTest>  Your not an admin
<@dgw>       .owner
<SopelTest>  Your not the owner
```

Set `-o+v` on myself:

```
<+dgw>       .voice
<SopelTest>  dgw: You may speak
<+dgw>       .halfop
<SopelTest>  Your not a halfop
<+dgw>       .op
<SopelTest>  Your not an operator
<+dgw>       .admin
<SopelTest>  Your not an admin
<+dgw>       .owner
<SopelTest>  Your not the owner
```

Do come back with more details if you can, and want to continue pursuing this, but it really doesn't seem to be an issue in Sopel itself. (Note: I tested Sopel 6.6.8. If you are using an older version, update and see if you can still reproduce with your "not working" plugin file.)

**Comment by ThijsEigenwijs** [comment] 2019-05-10 09:09
I cloned it yesterday, so think its a serverside issue! Thanks anyway for your time!

**Comment by dgw** [comment] 2019-05-10 09:10
If you haven't already, enable Sopel's `raw_log`, which should let you see any errors that come back from the IRC server if this continues happening. Best of luck debugging!
