### ISSUE TITLE
Sopel is not starting after a timeout on python 3.7

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#1888] opened 2020-06-09 08:49 UTC
### Description
When #1868 occurs on 3.7 we get a lot of log spam from #1865 in between
> [2020-06-09 04:46:41,529] sopel.irc.backends   INFO     - Closed!

and

> [2020-06-09 04:46:43,538] sopel.irc.backends   INFO     - Connection closed...

but the connection never recovers

### Reproduction steps
1. Install latest sopel & python 3.7 and install the https://github.com/Pix1234/ZppixBot-Source/tree/dev plugins
2. Wait awhile
3. #1868 occurs
4. Bot doesn't auto reboot

### Expected behavior
The two linked issues to not occur but if they do, it should recover automatically

### Logs
see https://phabricator.wikimedia.org/T254348#6204886 and https://phabricator.wikimedia.org/T254348#6204907
### Environment
- Sopel `.version`: 7.0.4 
- Sopel installed via: pip
- Python version: 3.7.3
- Operating system: Debian GNU/Linux 9.8 (stretch)
- IRCd `/version`: ircd-seven-1.1.9(20191023-4b033a7b9221,charybdis-3.4-dev). wolfe.freenode.net eHIKMpSZ6 TS6ow 32N
- Relevant plugins: Nothing touches memory

### Notes
As far as I can see, find_lines shouldn't be being touched at that point as the connection never fully starts so of course it will be empty

**Comment by RhinosF1** [comment] 2020-06-09 08:55
The full log seems to show it just keeps looping around with 
`[2020-06-09 04:46:41,529] sopel.irc.backends   INFO     - Connection closed...
[2020-06-09 04:46:41,529] sopel.bot            INFO     - Stopping the Job Scheduler.
[2020-06-09 04:46:41,529] sopel.bot            INFO     - Job Scheduler stopped.
[2020-06-09 04:46:41,529] sopel.bot            INFO     - Calling shutdown for 0 plugins.
[2020-06-09 04:46:41,529] sopel.irc.backends   INFO     - Closed!
[2020-06-09 04:46:41,535] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot-test at 2020-06-09 04:46:41.535755. Message was: [2020-06-09 04:46:39,527] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot-test at 2020-06-09 04:46:39.527121. Message was: [2020-06-09 04:46:37,517] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot-test at 2020-06-09 04:46:37.517694. Message was: [2020-06-09 04:46:35,507] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot-test at 2020-06-09 04:46:35.507173. Message was: [2020-06-09 04:46:33,496] s
Traceback (most recent call last):
  File "/data/project/zppixbot-test/zppixbottest37/lib/python3.7/site-packages/sopel/bot.py", line 606, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot-test/zppixbottest37/lib/python3.7/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot-test/zppixbottest37/lib/python3.7/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-06-09 04:46:43,538] sopel.irc.backends   INFO     - Connection closed...
[2020-06-09 04:46:43,538] sopel.bot            INFO     - Stopping the Job Scheduler.`

until it eventually gives up. This has never happened on python 3.7

**Comment by MyWay** [comment] 2020-06-15 16:28
Same here, but on 3.5.3.

**Comment by RhinosF1** [comment] 2020-06-15 16:34
> Same here, but on 3.5.3 running Sopel 7.0.4. I get an IRC timeout and sopel doesn't reconnect.

I've have never seen this bug on python 3.5.3 - do you have any debug logs?

The only time python 3.5.3 breaks is when I break it or the starter script is broke not sopel.

**Comment by MyWay** [comment] 2020-06-15 16:35
It happens frequently to me, so yes, I can add logs.

**Comment by RhinosF1** [comment] 2020-06-15 16:37
Please ensure logging_level is set to DEBUG

**Comment by MyWay** [comment] 2020-06-15 16:45
Ok, restarted with logging_level set to DEBUG.

**Comment by MyWay** [comment] 2020-06-17 16:46
```
[2020-06-16 23:25:23,636] sopel.irc.backends   ERROR    - Server timeout detected after 112s; closing.
[2020-06-16 23:25:23,688] sopel.irc.backends   INFO     - Connection closed...
[2020-06-16 23:25:23,720] sopel.bot            INFO     - Stopping the Job Scheduler.
[2020-06-16 23:25:24,049] sopel.bot            INFO     - Job Scheduler stopped.
[2020-06-16 23:25:24,061] sopel.bot            INFO     - Calling shutdown for 1 plugins.
[2020-06-16 23:25:24,072] sopel.bot            DEBUG    - Calling sopel.coretasks.shutdown
[2020-06-16 23:25:24,083] sopel.irc.backends   DEBUG    - Closing socket
[2020-06-16 23:25:24,144] sopel.irc.backends   INFO     - Closed!
```

**Comment by Exirel** [comment] 2020-06-17 17:29
And that's all? Nothing else before and/or after that? That's a bit thin. :-/

**Comment by MyWay** [comment] 2020-06-17 18:07
Yes, before it I had a long list of:
`sopel.coretasks      DEBUG    - Sending WHO for channel: #mychan`
which I thought were unrelated.

**Comment by Exirel** [comment] 2020-06-17 18:34
But what happen after that? What does your bot? Is there anything in the exceptions log file?

**Comment by MyWay** [comment] 2020-06-17 18:35
Nothing, I have to kill it and restart.Can't see anything inside default.exceptions.log.

**Comment by dgw** [comment] 2020-06-17 18:37
Weird. Getting disconnected by timeout or whatever without setting the status flags to quit or restart should pass through this whole block, log a warning _after_ the "Closed!" info line, and reach the `sleep()`, then restart the loop and connect again. But it's not?

https://github.com/sopel-irc/sopel/blob/b57578795a4bcdd120f6d2c2936fbf69a2915da1/sopel/cli/run.py#L117-L124

Thought I had a tenuous lead when I spotted `if not isinstance(delay, int): break`, but it looks like nothing ever touches the value assigned way up at the top, so… WTF. 😕

**Comment by Exirel** [comment] 2020-06-17 18:39
> Nothing, I have to kill it and restart.Can't see anything inside default.exceptions.log.

How long did you wait before killing it? Maybe you have a thread that takes too to end, or maybe you kill it before it can goes into the reconnecting state?

**Comment by MyWay** [comment] 2020-06-17 18:40
I waited 20 hours, about.

**Comment by MyWay** [comment] 2020-06-17 18:41
If you want to try anything I can modify the code, in 1-2 days it will happen again.

**Comment by RhinosF1** [comment] 2020-06-24 16:00
I can't reproduce after cleaning pyc files, reinstalling everything from pip and resetting it's cache

**Comment by dgw** [comment] 2020-06-25 19:52
Closing per @RhinosF1 (both here and on IRC).

@MyWay Please try cleaning up Python's cached bytecode etc. (`*.pyc` files, `__pycache__` directories, and so on). Unfortunately your logs don't show anything useful, but they're no less helpful than the ones we got from @RhinosF1 about this, so I'm guessing if you also clean up your installation you'll get similar success. 😸

**Closed by dgw** 2020-06-25 19:52 UTC
Labels: Bug

**Comment by MyWay** [comment] 2020-07-03 19:20
How do you delete the cache if installing from pip?

**Comment by Exirel** [comment] 2020-07-03 22:34
@MyWay you can try to uninstall Sopel with pip, than re-install it?

**Comment by MyWay** [comment] 2020-07-05 07:22
I did, same happens.

**Comment by RhinosF1** [comment] 2020-07-05 07:23
> I did, same happens.

See if pip has any caches, also delete any pyc files for the system.

**Comment by MyWay** [comment] 2020-07-05 07:44
I have installed it with the no cache flag, so I don't think. About system pyc files I have no idea where they can be.

**Comment by RhinosF1** [comment] 2020-07-05 07:48
> I have installed it with the no cache flag, so I don't think. About system pyc files I have no idea where they could be.

Anywhere on the filesystem so cd to / and then run "find . -name "*.pyc" -delete && find . -type d -empty -delete" which will remove any pyc files and delete empty directories. I strongly suggest backups before though and being extremely careful in what you remove. You can replace -delete with -print to dry run it.

**Comment by MyWay** [comment] 2021-01-16 21:38
Changed server too, now on python 3.7.3, but still having this issue. Any hint on how to find the root cause?

**Comment by dgw** [comment] 2021-01-17 22:25
All I can say is see if this still happens on current `master`. Without anything useful in debug logs, the next step would be running under a debugger (pdb or strace), which would generate a LOT of output to sift through if it still takes a few days to reproduce.

**Comment by MyWay** [comment] 2021-01-21 22:20
I see. I'm trying to disable plugins one at time. Could it be related to the whois plugin? It seems it's not happening anymore.

**Comment by dgw** [comment] 2021-01-21 22:25
Could be. What's a `whois` plugin, and how does it work? We don't ship one.

**Comment by MyWay** [comment] 2021-01-21 22:28
It was shipped under sopel-extras. Don't know if you replaced programmatically whois in some way.

**Comment by RustyBower** [comment] 2021-01-21 22:29
From the sopel-extras repo "Broken Sopel modules you might pick up and fix if you want them. Probably faster to just rewrite, though"

**Comment by dgw** [comment] 2021-01-21 22:33
Indeed, the sopel-extras repo:

* is archived
* contains a disclaimer in its description that its contents are likely broken
* contains even more disclaimers in the README that the plugins were removed from Sopel at some point due to conflicts, breakage, or other weirdness

We really don't support stuff in sopel-extras, and I suggest not using those plugins, _maybe_ except for very simple ones like 8ball.

**Comment by MyWay** [comment] 2021-01-21 22:37
I see, thanks. Are you aware of any other solution to have the whois command inside sopel and get the result?

**Comment by dgw** [comment] 2021-01-21 22:48
I can't even see how to trigger a WHOIS from that `whois.py` file in sopel-extras. It has no commands, so you must have some kind of wrapper or an edited copy. I guess it _could_ be part of the cause for this issue, but seems unlikely…

That said, even if it's completely unrelated, you'd probably be better off writing a new WHOIS plugin that handles things a bit differently. For example, polling for a result using `@module.interval` instead of a loop with `sleep()`, or catching more WHOIS-related numerics and posting the result back only when receiving 318 `RPL_ENDOFWHOIS`. If you aren't up to writing one, maybe someone in #sopel on freenode would be interested in doing it.

**Comment by MyWay** [comment] 2021-01-21 22:54
I see, thanks. I'll wait some days to confirm the problem is somewhere there and then proceed like you said.

**Comment by RhinosF1** [comment] 2021-01-21 22:55
I'm happy if you poke me over at phab.bots.Miraheze.wiki to consider taking ownership under @MirahezeBots of the Whois plugin. It doesn't look like that much of maintenance burden.

**Comment by Exirel** [comment] 2021-01-21 23:34
> For example, polling for a result using `@module.interval` instead of a loop with `sleep()`

The fact is: if the `sleep()` is called in a non-threaded function while the bot is trying to start, you will have problem, because it uses an io-loop, and not threads, to function. Any blocking I/O (such as synchronous `sleep()`) will block the bot.

That being said, I'd try the bot without any extra plugins, just to be sure, and see what happens. Good luck finding the source of your problem, and I hope the root cause will because obvious soon enough so it can be fixed - either on your side, or by Sopel itself.

**Comment by MyWay** [comment] 2021-01-25 20:24
Unfortunately that wasn't the problem. I have now disabled all plugins, let's see what happens.
