### ISSUE TITLE
Channel logging still attempts to output after connection loss

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#1865] opened 2020-05-20 09:34 UTC
### Description
After the bot reconnects to irc, we have a lot of logspam from find_lines not being in memory.

The bot is reconnecting following a network timeout.

### Expected behavior
We should not get logspam as find_lines should be set in memory or handled.

### Logs
```
[2020-05-19 21:11:48,217] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot-test at 2020-05-19 21:11:48.217625. Message was: [2020-05-19 21:11:48,209] sopel.cli.run        WARNING  - Disconnected. Reconnecting in 20 seconds...
Traceback (most recent call last):
  File "/data/project/zppixbot-test/zppixbottest/lib/python3.5/site-packages/sopel/bot.py", line 606, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot-test/zppixbottest/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot-test/zppixbottest/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-05-19 21:11:48,518] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot-test at 2020-05-19 21:11:48.518611. Message was: [2020-05-19 21:11:48,217] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot-test at 2020-05-19 21:11:48.217625. Message was: [2020-05-19 21:11:48,209] sopel.cli.run        WARNING  - Disconnected. Reconnecting in 20 seconds...Traceback (most recent call last):  File "/data/project/zppixbot-test/zppixbottest/lib/python3.5/site-packages/sopel/bot.py", line 606, in call    exit_code = func(sopel, trigger)  File "/data/project/zppixbot-test/zppixbottest/lib/
Traceback (most recent call last):
  File "/data/project/zppixbot-test/zppixbottest/lib/python3.5/site-packages/sopel/bot.py", line 606, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot-test/zppixbottest/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot-test/zppixbottest/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
```

### Environment
- Sopel `.version`: 7.0.3
- Sopel installed via: @Pix1234 ?
- Python version: Python 3.5.3
- Operating system: Debian 4.9.144-3 (2019-02-02) x86_64
- IRCd `/version`: Freenode

**Comment by dgw** [comment] 2020-05-20 17:26
What's going on here with "Message was" showing previous log lines, nested like Matryoshka dolls?

Does this happen forever (until Sopel is restarted) after a disconnect/reconnect cycle, or does it only "logspam" while the bot is actually disconnected?

**Comment by RhinosF1** [comment] 2020-05-20 17:52
> What's going on here with "Message was" showing previous log lines, nested like Matryoshka dolls?
> 
> Does this happen forever (until Sopel is restarted) after a disconnect/reconnect cycle, or does it only "logspam" while the bot is actually disconnected?

While the bot is disconnected + shortly after reconnecting rarely
Also happens when a reminder using remind.py is set before the disconnect but reminds after.

**Comment by dgw** [comment] 2020-05-20 18:48
> That’s because the bot tries to send a message to irc saying it’s disconnected even though it’s disconnected.

I take it you have IRC channel logging set up? The channel-logging facility _should_ handle the case when the bot isn't connected yet or loses connection. This might be (most of) the root cause here.

> While the bot is disconnected + shortly after reconnecting rarely

OK, that's probably related to messages getting sent to IRC by the logger when there's no connection.

> Also happens when a reminder using remind.py is set before the disconnect but reminds after.

If you can manage to get logs of this error, it would be useful. It doesn't sound related to the same cause as `find_lines`, but I can't be sure yet.

**Comment by RhinosF1** [comment] 2020-05-20 18:51
> > That’s because the bot tries to send a message to irc saying it’s disconnected even though it’s disconnected.
> 
> I take it you have IRC channel logging set up? The channel-logging facility _should_ handle the case when the bot isn't connected yet or loses connection. This might be (most of) the root cause here.

Yes

> > While the bot is disconnected + shortly after reconnecting rarely
> 
> OK, that's probably related to messages getting sent to IRC by the logger when there's no connection.
> 
> > Also happens when a reminder using remind.py is set before the disconnect but reminds after.
> 
> If you can manage to get logs of this error, it would be useful. It doesn't sound related to the same cause as `find_lines`, but I can't be sure yet.

Yeah, I’m going to reproduce that locally for the trace later.

**Comment by RhinosF1** [comment] 2020-05-21 09:15
> > Also happens when a reminder using remind.py is set before the disconnect but reminds after.
> 
> If you can manage to get logs of this error, it would be useful. It doesn't sound related to the same cause as `find_lines`, but I can't be sure yet.
[2020-04-16 18:54:59,077] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:54:59.077815. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:54:59,430] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:54:59.430301. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:54:59,451] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:54:59.451512. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:54:59,466] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:54:59.466491. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:54:59,665] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:54:59.665349. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:55:00,280] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:55:00.280909. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:55:00,911] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:55:00.911742. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:55:00,922] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:55:00.922281. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:55:01,003] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:55:01.003431. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:55:01,329] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:55:01.329682. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:55:01,354] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:55:01.354136. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'
[2020-04-16 18:55:01,360] sopel.bot            ERROR    - Unexpected error ('find_lines') from ZppixBot at 2020-04-16 18:55:01.360508. Message was: RhinosF1: The developers of ZppixBot would like to thank all frontline and key workers for their efforts against CoronaVirus and remind everyone to take this moment to #ClapForOurCarers. Stay Home, Stay Safe, Protect Lives. From, The ZppixBot Team.
Traceback (most recent call last):
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/bot.py", line 590, in call
    exit_code = func(sopel, trigger)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/module.py", line 495, in guarded
    return function(bot, trigger, *args, **kwargs)
  File "/data/project/zppixbot/lib/python3.5/site-packages/sopel/modules/find.py", line 43, in collectlines
    if trigger.sender not in bot.memory['find_lines']:
KeyError: 'find_lines'

**Comment by RhinosF1** [comment] 2020-05-21 10:30
https://git.io/Jfg1x fixed the reminders issue as it's now fully updated

**Comment by RhinosF1** [comment] 2020-05-22 15:19
while it’s [dis|re]connecting, we are still seeing the error.

We are working on updating and upstreaming/removing/actually making a plugin for all core hacks

**Comment by dgw** [comment] 2020-06-09 21:46
RhinosF1 confirmed with testing (high confidence, 90-95%) that `@echo` callables cause this in conjunction with `logging_channel` being on, because the bot then tries to handle its own logging messages and explodes. I'm guessing #1873 will make fixing this easier if it isn't already.

**Comment by dgw** [comment] 2020-06-24 23:06
#1890 should have fixed/closed this: https://github.com/sopel-irc/sopel/pull/1890/files#diff-4b53e7837a09fc93bf1d12ddfd1d6f17R32-R34

**Closed by dgw** 2020-06-24 23:06 UTC
Labels: Bug, High Priority
