### ISSUE TITLE
http://$ makes my Sopel puke with errors.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1150] opened 2016-11-26 19:51 UTC
Maybe a bug?
```
...
[11:49am] <Ant> http://$
11:49AM <URL> requests.exceptions.ConnectionError: HTTPConnectionPool(host='$',
          port=80): Max retries exceeded with url: / (Caused by
          NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection
          object at 0x7f6e68134828>: Failed to establish a new connection: [Errno -2]
          Name or service not known',)) (file
          "/home/ant/SopelPython3/lib/python3.4/site-packages/requests/adapters.py",
          line 487, in send)
[11:49am] <Ant> haha
[11:49am] <Ant> http://
[11:49am] <Ant> That's a bug.
11:50AM <R_Daneel> not necessarily
[11:50am] <Ant> He shouldn't puke!
11:50AM <R_Daneel> it's just he doesn't know how to handle string functions.
[11:51am] <Ant> We'll see what Sopel developers say!
11:51AM <R_Daneel> it's a lack of a feature, rather than a bug.
...

```
Thank you in advance. :)

**Comment by dgw** [comment] 2018-03-23 11:30
Special case duplicate of #1190.

**Closed by dgw** 2018-03-23 11:30 UTC
