### ISSUE TITLE
Twitter Character Limits

### ISSUE THREAD

**Issue by UncleanlyCleric** [sopel-irc/sopel#1348] opened 2018-06-25 18:09 UTC
Has there been any discussion regarding the newer 240 character limit to tweets?  It's not uncommon for my bot to not complete the whole tweet even though the IRC server would allow it.

I found a few places in the configs where there was a character limit of 140, and attempted to change them to 280 with no real effect.

Thanks

**Comment by dgw** [comment] 2018-06-25 19:39
Sopel doesn't do anything with tweets, except for the URL module fetching titles when tweet links are posted. Are you perhaps reporting an issue with [sopel-twitter](https://github.com/sopel-irc/sopel-twitter)?

**Comment by UncleanlyCleric** [comment] 2018-06-25 19:43
Ah.  That answers my question.  If Twitter is character limiting the title then that would be why.

**Comment by dgw** [comment] 2018-06-25 21:29
If I fetch the HTML for a lengthy tweet (while logged out, since Twitter returns a stub page that redirects with JavaScript if I'm logged in…), I get the whole tweet in the `<title>` tag. So I don't think it's Twitter.

But the URL module doesn't try to make its lines as long as absolutely possible. At most, it will use only the first 200 characters of any given title:

https://github.com/sopel-irc/sopel/blob/a0c567c09083414d20ad4f989012f80062d6d2fa/sopel/modules/url.py#L211

If you want the full text of linked tweets, install one of the Twitter modules and `url.py` will stop giving you its truncated versions. I'll close this, as this seems to be "Working as Intended". :smile_cat:

Should you want to follow any progress on making Sopel dynamically use as much of available IRC line space as possible, subscribe to #1322 (which is a prerequisite) and #1328 (one possible solution).

**Closed** 2018-06-25 21:29 UTC
