### ISSUE TITLE
.g (DuckDuckGo) showing yahoo ads again

### ISSUE THREAD

**Issue by dasu** [sopel-irc/sopel#1210] opened 2017-07-27 16:37 UTC
.g is starting to show yahoo ads again instead of relevant links.

To resolve, open search.py replace line 36 with:
`r_duck = re.compile(r'nofollow" class="[^"]+" href="(?!(?:https?:\/\/r\.search\.yahoo)|(?:https?:\/\/duckduckgo\.com\/y\.js))(.*?)">')` 

~~and in line 47, change `m.group(1)` to `m.group(3)`~~

~~(If anyone is really good at regex and know how to make it the first group, feel free to share)~~

**Comment by antdude** [comment] 2017-09-16 22:52
Which search.py do I edit to fix this issue?

$ locate search.py
/home/ant/SopelPython3/lib/python3.4/site-packages/pip/commands/search.py
/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search.py
/usr/lib/python2.7/dist-packages/pip/commands/search.py
/usr/lib/python2.7/dist-packages/pip/commands/search.pyc
/usr/share/doc/python-xapian/examples/simplesearch.py

**Comment by dasu** [comment] 2017-09-17 03:48
Your second one ( /home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search.py )
Hopefully it's line 36... otherwise whatever starts with r_duck = ...

**Comment by antdude** [comment] 2017-09-17 03:58
Thanks Dasu, but it didn't seem to fix mine:
[08:56pm] <Ant> .g test
08:56PM <URL> Ant: /l/?kh=-1&uddg=https%3A%2F%2Fwww.speedtest.net%2F
[08:56pm] <Ant> .g ant
08:56PM <URL> Ant: /l/?kh=-1&uddg=http%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCEfdlFLFtqXDIrrbWy78peQ

I see:
Function get is deprecated.
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 470, in call
    exit_code = func(sopel, trigger)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search.py", line 78, in duck
    result = duck_api(query)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search.py", line 62, in duck_api
    results = json.loads(web.get(uri))
Function get is deprecated.
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 470, in call
    exit_code = func(sopel, trigger)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search.py", line 84, in duck
    uri = duck_search(query)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search.py", line 41, in duck_search
    bytes = web.get(uri)

**Comment by dasu** [comment] 2017-09-18 20:19
Ah sorry, I personally took sopel's search.py made quite a bit of changes and saved it as search2.py, and put the original search.py in ignore list in the sopel config.
Here is my current version: https://github.com/dasu/syrup-sopel-modules/blob/master/search2.py
Some of the changes include: using the US version of bing and ddg instead of the UK version, converted all instances of sopel.web (because it's depreacted and thats what your 'error' message is showing) to requests library, and use a chrome header so it doesn't run into issues.

**Comment by antdude** [comment] 2017-09-18 20:25
Thanks dasu. Hmm, mine failed to load your search2.py (renamed the original search.py file so it won't be loaded):

(SopelPython3):~/SopelPython3/lib/python3.4/site-packages/sopel/modules$ sopel

Welcome to Sopel. Loading modules...


Error loading reddit: cannot import name 'Reddit' (../praw/__init__.py:14)
Error loading xkcd: No module named 'sopel.modules.search' (modules/xkcd.py:11)
Error loading search2: EOL while scanning string literal (search2.py, line 45) (modules/<frozen importlib._bootstrap>:321)
Error loading habitica: invalid syntax (common.py, line 25) (../sopel_modules/habitica/__init__.py:7)


Registered 42 modules,
4 modules failed to load

**Comment by dasu** [comment] 2017-09-18 20:31
Oh jeez, this always happens cause i'm a lazy pos that doesn't use GIT.
I fixed it.

**Comment by antdude** [comment] 2017-09-18 20:43
Ha. It happens. I do it too! Perfect and thanks:
...
[01:42pm] <Ant> .g test
01:42PM <URL> Ant: http://www.test.com/
[01:42pm] <Ant> YESS!!!!!!!!!!
[01:42pm] <Ant> .g ants
01:42PM <URL> Ant: https://en.wikipedia.org/wiki/Ant
...

**Comment by dgw** [comment] 2018-03-21 23:58
@dasu Is this still relevant? If so, would you mind submitting a PR with your fix?

**Comment by dasu** [comment] 2018-03-22 14:02
@dgw seems so, do you mind if I replace search.py with my own [search.py](https://github.com/dasu/syrup-sopel-modules/blob/master/search2.py), it resolves this issue as well as does away with sopel web (which is deprecated and gives a warning in the log every single time .g is called), it also defaults to US ddg/bing results instead of UK.

I'm so happy someone is finally in charge of this repo again.

**Comment by dgw** [comment] 2018-03-22 22:27
@dasu Let's fix the issue, then look at the refactor. All the changes you've made can probably go in 6.5.2, but it's in our (OK, _my_ :laughing:) best interest to keep code reviews small and manageable while I'm still processing the backlog of issues & PRs.

It looks like fixing this issue specifically is just a line or two, so start with that. Changing the target search locale from `en-GB` to `en-US` (or `uk-en` to `us-en`, thanks DDG for those oddball codes) is another small change set, and a separate thing that deserves its own PR. Factoring out `sopel.web` is a bigger thing that _definitely_ deserves its own PR, since it touches a fair few lines and changes how some things are handled. (Fair warning: I am not entirely happy with a simple `replace("&amp;","&")` on DDG results, in case there are other HTML entities added later. It's not future safe.)

Another tweak that isn't in your updated search module, but could be done, is switching to call HTTPS APIs where possible. DDG and Bing certainly both support HTTPS, and in 2018 it's silly to request search results over a plain-text connection. (This could probably combine with changing the search locales as a general "Update API URLs" PR, if you don't want to add yet another.)

**Comment by dgw** [comment] 2018-03-29 08:37
@dasu I'll look forward to your search module updates for 6.6.0. :) It kind-of works in 6.5.2-dev right now, and that's good enough until a bigger rewrite if you're up for it.

**Comment by dgw** [comment] 2018-03-29 10:15
Also, closing this issue because I've been unable to reproduce it during testing as I tweaked several pieces of the existing search module. Anyone is welcome to post examples if they can reproduce.

**Closed by dgw** 2018-03-29 10:15 UTC
Labels: Bug, Easyfix, Tweak
