### ISSUE TITLE
TypeError: buf must be a byte string (file "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall)

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#996] opened 2016-01-11 19:47 UTC
Hello.

[11:45am] <Ant> https://www.reddit.com/r/OldSchoolCool/comments/3zf5gz/parkour_1930s/
11:45AM <URL> TypeError: buf must be a byte string (file
          "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall)
[11:45am] <Ant> hmmmmmmmmmmmmmmmmm
[11:46am] <Ant> .version
11:46AM <URL> Ant: Sopel v. 6.1.1

Any ideas? Thank you in advance. :)

**Comment by maxpowa** [comment] 2016-01-12 02:05
Most likely related to this https://github.com/pyca/pyopenssl/issues/15. PRAW is probably passing something to pyopenssl that it doesn't like. Some people have reported updating to python 2.7.10 has resolved the issue. Running Sopel with `python3` would also solve the issue.

**Comment by antdude** [comment] 2016-01-12 03:05
$ python
Python 2.7.9 (default, Mar  1 2015, 12:57:24)
[GCC 4.9.2] on linux2

$ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux

So, how do I tell Sopel to use Python v3? Both Python packages were from Debian stable (Jessie).

**Comment by maxpowa** [comment] 2016-01-12 03:35
I always recommend using virtualenv.
```
pip install virtualenv
virtualenv -p python3 <some_folder>
source <some_folder>/bin/activate
pip install sopel
sopel
```

You can of course do so without virtualenv
```
pip uninstall sopel
pip3 install sopel
sopel
```

**Comment by antdude** [comment] 2016-01-12 03:56
Hmm, pip3 doesn't exist in Debian's packages? I got python-pip package, but it didn't have pip3. I tried that virtualenv thing:

$ sudo pip install virtualenv
Downloading/unpacking virtualenv
  Downloading virtualenv-13.1.2-py2.py3-none-any.whl (1.7MB): 1.7MB downloaded
Installing collected packages: virtualenv
Successfully installed virtualenv
Cleaning up...
$ virtualenv -p python3 test/
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in test/bin/python3
Also creating executable in test/bin/python
Installing setuptools, pip, wheel...done.
$ source test/bin/activate
(test)$ pip install sopel
Collecting sopel
  Downloading sopel-6.1.1.tar.gz (100kB)
    100% |████████████████████████████████| 102kB 603kB/s
Collecting xmltodict (from sopel)
  Downloading xmltodict-0.9.2.tar.gz
Collecting pytz (from sopel)
  Downloading pytz-2015.7-py2.py3-none-any.whl (476kB)
    100% |████████████████████████████████| 479kB 798kB/s
Collecting praw (from sopel)
  Downloading praw-3.3.0-py2.py3-none-any.whl (69kB)
    100% |████████████████████████████████| 69kB 2.4MB/s
Collecting pyenchant (from sopel)
  Downloading pyenchant-1.6.6-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 2.7MB/s
Collecting pygeoip (from sopel)
  Downloading pygeoip-0.3.2-py2.py3-none-any.whl
Collecting six>=1.4 (from praw->sopel)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting decorator>=3.4.2 (from praw->sopel)
  Downloading decorator-4.0.6-py2.py3-none-any.whl
Collecting requests>=2.3.0 (from praw->sopel)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 503kB 743kB/s
Collecting update-checker>=0.11 (from praw->sopel)
  Downloading update_checker-0.11-py2.py3-none-any.whl
Building wheels for collected packages: sopel, xmltodict
  Running setup.py bdist_wheel for sopel
  Stored in directory: /home/ant/.cache/pip/wheels/ae/7d/84/fe4d59b407fe0180230b7c41c81fd759d71899eed32cba3ac8
  Running setup.py bdist_wheel for xmltodict
  Stored in directory: /home/ant/.cache/pip/wheels/ac/89/8d/1d837ec2a459406472f0586d7fe560dc9dec5bc87c4f171a2b
Successfully built sopel xmltodict
Installing collected packages: xmltodict, pytz, six, decorator, requests, update-checker, praw, pyenchant, pygeoip, sopel
Successfully installed decorator-4.0.6 praw-3.3.0 pyenchant-1.6.6 pygeoip-0.3.2 pytz-2015.7 requests-2.9.1 six-1.10.0 sopel-6.1.1 update-checker-0.11 xmltodict-0.9.2
(test)$ sopel -d
(test)$
Welcome to Sopel. Loading modules...
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Registered 40 modules,
1 modules failed to load
Connecting to irc...:6697...
Connected.

I checked in my BitchX IRC client and tested it:
[07:53pm] <Ant> https://github.com/sopel-irc/sopel/issues/996
07:53PM <URL> [ TypeError: buf must be a byte string (file
          "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969,
          in sendall) · Issue #996 · sopel-irc/sopel · GitHub ] -
          github.com

Um, still on Python v2.7? :/

**Comment by maxpowa** [comment] 2016-01-12 04:13
Wait, that's intended behavior. It's showing the title of this issue on github, which happens to be the `TypeError: buf must be a byte string (file "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall)`

**Comment by antdude** [comment] 2016-01-12 04:24
Oh silly me! Haha.

[08:21pm] <Ant> https://www.reddit.com/r/OldSchoolCool/comments/3zf5gz/parkour_1930s/
08:21PM <URL> [REDDIT] Parkour 1930's (http://imgur.com/P8lAFQk.gifv) to r/OldSchoolCool | 5243
          points (95.0%) | 280 comments | Posted by SlimJones123 | Created at 01/04/16 07:17:12 AM
          AM -0800 PST
Yay!

So if I want to use Python 3 in the future with virtualenv, do I just do these commands?
virtualenv -p python3 <some_folder>
source <some_folder>/bin/activate
sopel

Same for updating, uninstalling, reinstalling, etc.?

**Comment by maxpowa** [comment] 2016-01-12 04:27
You'll only have to do the `source <venv>/bin/activate` to switch your python environment. So if you're updating/running/uninstalling etc to sopel you'll have to activate. The `virtualenv -p python3 folder` is just a one-off to generate the virtual python install.

**Comment by antdude** [comment] 2016-01-12 04:29
Thanks Maxpowa! I hope Debian can fix this issue in Python v2.7.

**Comment by antdude** [comment] 2016-01-17 17:27
Is this broken again in Sopel v6.2.1?

[09:24am] <Ant> https://www.reddit.com/r/OldSchoolCool/comments/3zf5gz/parkour_1930s/
09:24AM <URL> TypeError: buf must be a byte string (file
          "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall)

(sopel-python3)ant@Box:~/$
$ ls -all ~/sopel-python3/bin/
total 4420
drwxr-xr-x 2 ant ant    4096 Jan 17 09:22 .
drwxr-xr-x 4 ant ant    4096 Jan 17 02:59 ..
-rw-r--r-- 1 ant ant    2234 Jan 17 02:59 activate
-rw-r--r-- 1 ant ant    1260 Jan 17 02:59 activate.csh
-rw-r--r-- 1 ant ant    2473 Jan 17 02:59 activate.fish
-rw-r--r-- 1 ant ant    1137 Jan 17 02:59 activate_this.py
-rwxr-xr-x 1 ant ant     252 Jan 17 09:22 easy_install
-rwxr-xr-x 1 ant ant     252 Jan 17 09:22 easy_install-3.4
-rwxr-xr-x 1 ant ant     224 Jan 17 09:22 pip
-rwxr-xr-x 1 ant ant     224 Jan 17 09:22 pip3
-rwxr-xr-x 1 ant ant     224 Jan 17 09:22 pip3.4
lrwxrwxrwx 1 ant ant       7 Jan 17 09:22 python -> python3
-rwxr-xr-x 1 ant ant 4476488 Jan 17 09:22 python3
lrwxrwxrwx 1 ant ant       7 Jan 17 09:22 python3.4 -> python3
-rwxr-xr-x 1 ant ant     231 Jan 17 09:22 wheel

(sopel-python3)$ python
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

:(

**Comment by maxpowa** [comment] 2016-01-17 18:18
Looks like you forgot to activate your virtualenv before starting sopel, it's showing python 2.7 in the error you posted.

**Comment by antdude** [comment] 2016-01-17 18:52
Ah. Still using the global binary after uninstalling Sopel:

$ sopel -d
-bash: /usr/local/bin/sopel: No such file or directory

I went to my ~/SopelPython3/bin and ran sopel from there. Now, it works!

I'm learning a lot. Thanks again. :)

**Comment by elad661** [comment] 2016-01-29 19:05
Removing the Bug label from this issue. I'm not sure it's even our bug. Especially if people say that it's fixed with a newer python version and it's an issue with Praw itself.

@maxpowa I think I should close this issue. what do you think?

**Comment by maxpowa** [comment] 2016-01-29 19:38
Yeah, I'd agree with closing it as its a bug in PRAW, not us.

**Closed** 2016-01-29 19:52 UTC
