### ISSUE TITLE
[core]: Unicode issue in long messages

### ISSUE THREAD

**Issue by Erethon** [sopel-irc/sopel#467] opened 2014-03-02 14:20 UTC
There is a bug concerning unicode characters when a message is long enough.

Here, where the message is short, everything works correctly:

<pre>
Erethon: !in 10s τεστ
BuildTest: Erethon: Okay, will remind in 10 secs
BuildTest: Erethon: τεστ
</pre>

But, when the message is long enough:

<pre>
Erethon: !in 10s 
αααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααααα
BuildTest: Erethon: Okay, will remind in 10 secs
BuildTest: Erethon: 
Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î±Î
</pre>

This is marked as [core] because it happens in more than one module, I've confirmed it in ".py" too.
I'm using python 2.7.3 and latest Willie version from master branch and I've installed Willie by running 'python setup.py install'.

**Comment by maxpowa** [comment] 2016-06-22 21:40
I've had this happen when the message sent to the IRC server is trimmed in between bytes of the unicode characters. Probably caused by https://github.com/sopel-irc/sopel/blob/master/sopel/bot.py#L280-L300

**Comment by Exirel** [comment] 2019-01-13 20:37
Indeed, @maxpowa was right!

See this example:

```
>>> len('α')
1
>>> len('α'.encode('utf-8'))
2
```

To fix this, I'll provide a PR where I loop over the unicode string until the bytecode version is smaller.

**Comment by dgw** [comment] 2019-01-31 09:01
@Exirel Does #1448 close this completely, or only fix part of it?

**Comment by dgw** [comment] 2019-01-31 10:40
OK, I mostly asked because #1448 is going to be put in the next bugfix release. But if it doesn't fix all of this issue, then this one can stay in the 7.0 milestone and get worked on later.

**Comment by deathbybandaid** [comment] 2019-07-09 19:22
I still am interested in trying to reach the 512 limit, and even though my original PR got rejected, I did some work/research on figuring out how close to 512 we could safely get utilizing the `len()` of the bot's full hostmask, the recipients, and the reservation of length for the actual `PRIVMSG` or `NOTICE`.

The following code snippet even has a pretty explanatory docstring.

https://github.com/deathbybandaid/sopel/blob/b6ffa36592546cca90b7e684189133bcc5afb15b/sopel/tools/__init__.py#L274-L302


Even if we don't want to "support" multiple recipients, it can still be done manually (at the module/plugin level) with comma separation, and has an effect on the overall sendable `len()`.

**Comment by dgw** [comment] 2019-11-16 17:44
This will build on other improvements we already plan to make in 7.1, not 7.0.

**Comment by dgw** [comment] 2020-05-08 14:51
I can no longer reproduce this with Sopel 7.0.3 on Python 3.5. Tried multiple clients. Given that the issue is _literally_ six years old, I think it's safe to close it and let someone open a new one if they find a similar bug in the future.

**Closed by dgw** 2020-05-08 14:51 UTC
Labels: Bug
