### ISSUE TITLE
Add day, time and date to Seen module timestamp format.

### ISSUE THREAD

**Issue by kenjoe41** [sopel-irc/sopel#788] opened 2015-04-18 20:00 UTC
Seen modules now reports only the time the user was last seen irrespective of the fact that the user might have been seen a week ago.

I would be better for the module to report the day, time and probably the date the user was last seen and the message.

I also don't think it would be dangerous to include the channel the user was last seen in if it isn't this channel

**Comment by dgw** [comment] 2015-04-18 20:12
Channel display should probably respect secret (+s) channels at the very least, and maybe even exclude invite-only (+i) channels and/or key-access (+k) channels as well. Thoughts?

**Comment by tyrope** [comment] 2015-04-18 22:20
@dgw Hide +s and +p, show +i and +k (they can be seen in /list after all)

**Comment by dgw** [comment] 2015-04-18 22:48
@tyrope Ah, that's fair. Didn't actually know networks still used +p; thought it was obsoleted in favor of +s just about everywhere.

**Comment by embolalia** [comment] 2015-04-19 13:20
Re. hiding, see #189. TL;DR: WONTFIX.

Re. date:
```
<embolalia> .seen Tyrope 
<Willie> embolalia: I last saw Tyrope at Sun, 19 April 2015, 08:45:52 EDT in another channel.
```
I'm not sure what is missing.

**Comment by tyrope** [comment] 2015-04-19 14:05
```
[1604.49] <Tyrope> But it uses the timeformat from the user.
[1604.52] <Tyrope> .seen embolalia
[1604.53] <@Willie> Tyrope: I last saw embolalia at 2015-04-19T15:26:25+0200 in another channel.
```
Might want to do a .settimeformat

**Comment by kenjoe41** [comment] 2015-04-23 12:54
Thanks for fixing this.

**Comment by tyrope** [comment] 2015-04-23 13:32
@kenjoe41 What exactly is it you wish us to change? The date is reported if you set your timeformat correctly, the channel is [as stated above](https://github.com/embolalia/willie/issues/189) removed previously due to +s/p and hence not returning.

**Comment by embolalia** [comment] 2015-08-29 20:25
Can't reproduce, and no further information. Closing.

**Closed by embolalia** 2015-08-29 20:25 UTC
Labels: needinfo
