### ISSUE TITLE
When an IRC person leaves & returns, I get a traceback error...

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1005] opened 2016-01-20 06:54 UTC
Hello.

For an example:
...
��� SignOff Flexo: #bots,#linux (Quit: restarting, back in 5...)
10:51PM ��� Flexo [~rbot@[deleted its IP address] has joined #linux
...

$ Traceback (most recent call last):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/coretasks.py", line 375, in track_quit
    channel.clear_user(trigger.nick)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/tools/target.py", line 63, in clear_user
    user = self.users[nick]
KeyError: Identifier('Flexo')

Thank you in advance. :)

**Comment by thomastanck** [comment] 2016-01-24 03:11
I manually patched this in my copy since I was getting a similar thing. Can someone help patch this into sopel itself?

```diff
                              official            my copy
                         __________________   _______________
gracefu:~ gracefu$ diff "sopel-core 2/sopel" "sopel-core copy"
Only in sopel-core copy: __init__.pyc
Only in sopel-core copy: bot.pyc
Common subdirectories: sopel-core 2/sopel/config and sopel-core copy/config
diff sopel-core 2/sopel/coretasks.py sopel-core copy/coretasks.py
181a182
>         bot.users[nick] = User(nick, None, None)
357a359
>         bot.users[trigger.nick] = user
Only in sopel-core copy: coretasks.pyc
Only in sopel-core copy: db.pyc
Only in sopel-core copy: formatting.pyc
Only in sopel-core copy: irc.pyc
Only in sopel-core copy: loader.pyc
Only in sopel-core copy: logger.pyc
Only in sopel-core copy: module.pyc
Common subdirectories: sopel-core 2/sopel/modules and sopel-core copy/modules
Only in sopel-core copy: run_script.pyc
Only in sopel-core copy: test_tools.pyc
Common subdirectories: sopel-core 2/sopel/tools and sopel-core copy/tools
Only in sopel-core copy: trigger.pyc
Only in sopel-core copy: web.pyc
```

Reason why this occurs is that the bot.users dict is only populated when a user joins, but if you join a channel, bot.users is not populated. I added code to insert the user into bot.users after a NAMREPLY, but the problem is that you lose the username/hostname info that's stored in a User. Good enough for me.

The same problem will occur if you live on a silly IRC server which sends you QUIT messages of nicks you don't know of. To properly fix this, change line 63 in tools/target.py:
```diff
-        user = self.users[nick]
+        user = self.users.get(nick) # user == None if nick doesn't exist, rather than raising an exception
```

**Comment by maxpowa** [comment] 2016-01-29 02:41
@thomastanck I'd be willing to patch in your changes, but you don't show the line numbers of the two lines it looks like you've added in coretasks. If you provide those two I'd be happy to test and merge.

**Comment by embolalia** [comment] 2016-01-29 13:22
@thomastanck: In amongst everything else in your comment, I think you hit on the real issue here: "if you join a channel, bot.users is not populated". This is a bug, and it's a bug that'd cause the symptoms here.

So the question is, why is bot.users not getting populated when you join a channel? The bot does [send a WHO on JOIN](https://github.com/sopel-irc/sopel/blob/master/sopel/coretasks.py#L351), and [handle WHO replies](https://github.com/sopel-irc/sopel/blob/master/sopel/coretasks.py#L635-L672). So why is this not working properly? @thomastanck and @antdude: What IRC networks are you connecting to? I think this'll require some debugging of the traffic.

**Comment by thomastanck** [comment] 2016-01-29 13:48
@embolalia I'm connecting to irc.ppy.sh, an eccentric IRC server for in game chat for osu!.

Sopel does send a WHO command, where the server replies with 353s (RPL_NAMREPLY), followed by a 366 (RPL_ENDOFNAMES). I believe this is proper behaviour for IRC servers. But note that only nicks are provided. In my first diff (coretasks.py) you see I included a line (handle_names) which adds User(nick, None, None) to bot.users when NAMES are given, and the other line is in track_join where the user is added to bot.users (this time actually containing the username and hostname)

The first one (handle_names) is not fully solvable as we simply don't have the information User wants. We could get away with filling the hostname and username with None, and then adding them in when the opportunity arises.

The second one (track_join) is definitely a bug. I forgot I fixed that.

```
>>1454067516.82	CAP LS 302
>>1454067516.82	PASS *******
>>1454067516.82	NICK gracefu
>>1454067516.82	USER sopel +iw gracefu :Sopel: http://sopel.chat
<<1454067517.39	:cho.ppy.sh 001 gracefu :Welcome to the osu!Bancho.
>>1454067517.39	MODE  gracefu +B
>>1454067517.39	JOIN #osu

... ascii art ...

<<1454067517.6	:baldhi!cho@ppy.sh QUIT :quit
<<1454067517.8	:cho.ppy.sh 502 gracefu :Can't change mode for other users
<<1454067517.82	:gracefu!cho@ppy.sh JOIN :#osu
>>1454067517.82	WHO #osu
<<1454067517.82	:BanchoBot!cho@cho.ppy.sh MODE #osu +v gracefu
<<1454067517.82	:cho.ppy.sh 332 gracefu #osu :The official osu! channel (english only).
<<1454067517.82	:cho.ppy.sh 333 gracefu #osu BanchoBot!BanchoBot@cho.ppy.sh 1452356629
<<1454067517.82	:cho.ppy.sh 353 gracefu = #osu :cformis Vanted jjj31234 grando00637 LastWinterxxx kanda-101 oOKahlanOo +pieter12321 +Zman840 +morovaa Rikka karta1498598 [Caramel] tk0720 Majorca Asker767 kanes01 mu-san +Arteshin @Ephemeral @mm201 @peppy @Zallius +Pannari +RagingCactus vinnie0605 Skwigly 
<<1454067517.83	:cho.ppy.sh 353 gracefu = #osu :WalupBao +khazhyk dylanmcg2002 Iloh @Saten Cow_God Intx Arclight thorsmaster Kureha qaz090327 kjs19233 328340 Mikakunin berserker210 Forever_dai aitsuk Microsoft_Vista sirokuro22 +Rumi +Howl +MagicNAT +Delaxarnyazer +neico +Rokodo Shenronn grace01 Frostline17 

... metric ton of names here ...

<<1454067519.55	 gheod99 1271035694 Shredoctor MeschejrePL mikazuto MAJINGGAJAJI TutukakushiTukiko Th3M4st3rFr0st BIGPencill Freshlemon phoria39 AcidSnow1 Fumiko12 Spartan_117DI YouSteezz takahoko nolinemae killyou456 Gluck2040 Big_Lun A_meu_ lombit Babossetti KAIMAN 
<<1454067519.55	:cho.ppy.sh 353 gracefu = #osu :Toeto_Etoe Mitty51133 nurauliae jimm9v N_Lak OnTheS1ck CptDild0zr Dasha_o UchihaAlchemist Deniark27 NightKnight100 AungBodacity Haruna0Nagato Metal_Wolf ZimoHD OtakungHapon Syperek Asulan_deo waszak2000 phisical Flame125 Rhm_B_WT yukiyukicupcake yeow0905 XISHNIK 
<<1454067519.56	:cho.ppy.sh 353 gracefu = #osu :stalkerdenrus Alikhalik +gracefu 
<<1454067519.56	:cho.ppy.sh 366 gracefu #osu :End of /NAMES list.
<<1454067519.56	:smin8657!cho@ppy.sh QUIT :quit
<<1454067519.56	:White_Out!cho@ppy.sh QUIT :quit
<<1454067519.56	:AimNeet!cho@ppy.sh QUIT :quit
<<1454067519.56	:buszko24!cho@ppy.sh JOIN :#osu
<<1454067519.56	:slurpeefreeze!cho@ppy.sh QUIT :quit
<<1454067519.57	:nori19251!cho@ppy.sh JOIN :#osu
<<1454067519.57	:cho.ppy.sh 315 gracefu #osu :End of /WHO list.
<<1454067519.57	:NTNonPKA!cho@ppy.sh QUIT :ping timeout 80s
<<1454067519.57	:SebWU1999!cho@ppy.sh QUIT :quit
<<1454067519.57	:derpjussi!cho@ppy.sh QUIT :quit
<<1454067519.57	:XxFaLLeRxX!cho@ppy.sh JOIN :#osu
<<1454067519.57	:daredevillj!cho@ppy.sh QUIT :replaced (None 5ad392b7-6224-4083-a218-3ba1bccd7360)
<<1454067519.57	:daredevillj!cho@ppy.sh JOIN :#osu
<<1454067519.58	:salmamutii_!cho@ppy.sh JOIN :#osu
<<1454067519.58	:Taikoku_Yuki!cho@ppy.sh QUIT :quit
```

**Comment by embolalia** [comment] 2016-01-29 14:01
According to [RFC 1459](https://tools.ietf.org/html/rfc1459#section-4.5.1), the correct reply to WHO is 352 RPL_WHOREPLY. [WHOX](http://faerion.sourceforge.net/doc/irc/whox.var) specifies an alternative 354 RPL_WHOSPCRPL. This IRCd is blatantly ignoring the spec and common usage if it's sending 353 in response to WHOs. I suspect what it's actually doing is ignoring the WHO altogether. (Which, again, is against the spec. The least it could do is send 421 ERR_UNKNOWNCOMMAND.)

Supporting spec-breaking behavior for uncommon IRCds is outside the scope of this project. If @antdude is connecting to something different, which follows the spec, and is getting this error, this is still a valid bug. But I don't intend to add shims for broken servers.

**Comment by thomastanck** [comment] 2016-01-29 14:11
With this specific IRCd, the error occurs regardless of whether or not QUIT is sent for users not associated with Sopel. I see that the code to receive WHO replies does in fact populate bot.users properly; this is good since it means there's no error upon QUIT if WHO is used properly. However, since this IRCd is replying with NAMREPLY instead, Sopel does not populate bot.users.

If WHOREPLY is the proper response, and Sopel already handles WHOREPLY properly, then the PR would do nothing other than silence errors on a couple nonconforming servers. It would also mean there was technically no bug to begin with... x.x

**Comment by antdude** [comment] 2016-01-29 16:57
embolalia: It's a private IRCd server.

**Comment by embolalia** [comment] 2016-01-30 17:34
@antdude: Do you happen to know what IRCd software it uses?

**Comment by antdude** [comment] 2016-01-30 17:39
@embolalia: No, but let me ask the hosts who run them.

**Comment by maxpowa** [comment] 2016-01-30 18:06
@embolalia I have seen this issue inconsistently on espernet, which uses the charybdis ircd.

**Comment by antdude** [comment] 2016-01-30 21:32
OK, I got the answers: Ratbox and Hybrid.

**Comment by dgw** [comment] 2016-01-30 22:22
Ratbox looks pretty abandoned. Homepage says it was last updated in July 2012 and the project's bug tracker subdomain serves up a copy of the main site. That server should probably be moved to a different IRCd.

Hybrid was allegedly last committed to 2 hours ago. If Hybrid is serving up incorrect responses, chances are updating said private IRC server will fix it there—and if not, the developers should be reachable to fix it.

charybdis describes itself as "an extremely scalable ircd with some cooperation with the ratbox and ircu guys", so maybe that's why Ratbox appears to be dead? Might also be reason to suspect that some of the same glitches would be present in both daemons.

**Comment by dgw** [comment] 2016-02-02 08:16
After updating my bot instance on Rizon to 6.3.0 (from 5.5.1), I am now seeing these errors in the exception log. Can we get #1014 merged and a new release packaged to fix this? Too bad a fix for this didn't make it into 6.3.0.

**Comment by elad661** [comment] 2016-02-02 19:24
#1014 is not a fix, it just hides the actual problem

**Comment by dgw** [comment] 2016-02-02 20:22
I see. It looks like user handling in general under the new `bot.channels` system is pretty unfinished. I tried to migrate a module off of `bot.privileges` because it's deprecated, and the privileges aren't populated in the new system.

**Comment by elad661** [comment] 2016-02-02 20:43
I don't think it's unfinished. it's just that the IRC servers who has this problem do not conform with the spec... and it's @embolalia's choice whether to support these IRC servers or not. When using an IRC server that follows the spec properly, these problems don't occur.

**Comment by thomastanck** [comment] 2016-02-02 21:45
@elad661 Is right: It only hides the actual problem. But on compliant servers there is no problem.

Though I can make another PR with just the actual bugfix and nothing else: track_join isn't adding users to bot.users at the moment, just bot.channels. Due to a series of unfortunate events, this doesn't really trigger any exceptions (see my comments in #1014)

**Closed** 2016-05-25 16:03 UTC
Labels: Bug
