### ISSUE TITLE
Module API: Add ability to send message to user when they trigger a rate-limited command

### ISSUE THREAD

**Issue by kwaaak** [sopel-irc/sopel#1353] opened 2018-07-08 01:11 UTC
Some decorators like "require_privmsg" have a "message" option to reply to users who have not satisfied the requirement.
It would be nice if the "rate" decorator also had this functionality instead of the resulting silence.

**Comment by dgw** [comment] 2018-07-08 07:56
Duplicate of #830.

**Closed by dgw** 2018-07-08 07:56 UTC
