### ISSUE TITLE
Any way to disable wait time for messages

### ISSUE THREAD

**Issue by ThijsEigenwijs** [sopel-irc/sopel#1595] opened 2019-05-10 10:57 UTC
I'm building a bot, but it seems to throttle or have a delay between the messages it sends, is there any way te disable the delay?

I've tried the @rate, but it didn't seem to change anything

Example: Send a part of the chat log back in an OP channel

**Comment by dgw** [comment] 2019-05-10 11:29
Duplicate of #1216, #1407, and probably others.

This is not configurable at present. See #1342 and #1518. It's planned, just not quite ready yet.

**Closed by dgw** 2019-05-10 11:29 UTC
