### ISSUE TITLE
Unable to "git clone git://github.com/sopel-irc/sopel.git" ...

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#2517] opened 2023-10-06 20:39 UTC
### Description

$ git clone git://github.com/sopel-irc/sopel.git
Cloning into 'sopel'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection timed out

This happens in two different Linux boxes and two different ISPs. I am using "Latest source" instructions from https://sopel.chat/usage/installing/.

Thank you for reading and hopefully answering soon. :)

### Reproduction steps

$ git clone git://github.com/sopel-irc/sopel.git
Cloning into 'sopel'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection timed out

Thank you for reading and hopefully answering soon. :)

### Expected behavior

git clone should download Sopel's latest source. :(

### Notes

No problems with https://github.com though.

### Sopel version

8.0

### Installation method

My distro's package manager (apt, etc)

### Operating system

Debian Bullseye v11 and Fedora 35

**Comment by SnoopJ** [comment] 2023-10-06 20:42
This is not a problem with Sopel, the problem is that your `git` command is invalid. The command you want is:

```
git clone git@github.com:sopel-irc/sopel.git
```

**Comment by SnoopJ** [comment] 2023-10-06 20:45
Hmm, actually, this issue should stay open for now since the docs _do_ list the incorrect command.

**Comment by antdude** [comment] 2023-10-06 20:47
Woah, fast answer and thanks. Please update the outdated command in  https://sopel.chat/usage/installing/ web page's instructions for "Latest source". However, I ran into another issue on both PCs and ISPs:

$ git clone git@github.com:sopel-irc/sopel.git
Cloning into 'sopel'...
Warning: Permanently added the ECDSA host key for IP address '192.30.255.113' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by SnoopJ** [comment] 2023-10-06 20:49
> However, I ran into another issue on both PCs and ISPs:
> 
> $ git clone [git@github.com](mailto:git@github.com):sopel-irc/sopel.git Cloning into 'sopel'... Warning: Permanently added the ECDSA host key for IP address '192.30.255.113' to the list of known hosts. [git@github.com](mailto:git@github.com): Permission denied (publickey). fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights and the repository exists.

Looks like something is wrong with your system's SSH configuration, perhaps you have `github.com` listed in your `~/.ssh/config`. However, this issue tracker is for discussing _issues with Sopel itself_.

**Comment by dgw** [comment] 2023-10-06 21:13
Two things on this:

1. You need an SSH remote only for write access to the repository, and even pulling requires having your local SSH key authorized on the GitHub side.\* Regular users who aren't making contributions should probably use the read-only HTTPS clone URL.
2. This issue should be filed against [the website repo](https://github.com/sopel-irc/sopel.chat), if the incorrect instructions appear somewhere other than under `/docs/`. Only that subfolder is currently built from sources in the main Sopel repository.
   Rather than an issue, someone could easily just file a PR directly against the website, updating the installation instructions to match [the project README file](https://github.com/sopel-irc/sopel#installation).

_**\*:** "To use these URLs, you must generate an SSH keypair on your computer and add the **public** key to your account on GitHub.com." — https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-ssh-urls_

**Comment by dgw** [comment] 2023-10-06 21:20
Too much this-repo-specific stuff for my taste to transfer the issue. I opened a new one with the original problem statement: sopel-irc/sopel.chat#43

Since the installation instructions _in this repo_ are correct, I'll close this.

**Comment by dgw** [comment] 2023-10-06 21:33
Instructions on the site have been updated: https://sopel.chat/usage/installing/#latest-source

**Comment by dgw** [comment] 2023-10-06 21:51
@antdude [pointed out](https://github.com/sopel-irc/sopel.chat/issues/43#issuecomment-1751437220) an error in the README docs, where what should be a source zip for `master` points to the latest _release_ instead.

**Comment by antdude** [comment] 2023-10-06 21:53
Thanks again, dgw. In the past, I always just used basic git clone method without any fancy logins and setups. Now, it got really complicated and strict. "git clone https://github.com/sopel-irc/sopel.git"  was the perfect answer. No errors in my Debian. I just need to get my friend to fix his Fedora's access since I'm just a regular SSH2 user (no root/sudo) due to: 
$ git clone https://github.com/sopel-irc/sopel.git
Cloning into 'sopel'...
fatal: unable to access 'https://github.com/sopel-irc/sopel.git/': error setting certificate file: /etc/pki/tls/certs/ca-bundle.crt

For now, I will just use https://github.com/sopel-irc/sopel/archive/refs/heads/master.zip on it and git clone method in my Debian PC.

**Closed** 2023-10-06 22:03 UTC
Labels: Documentation
